version: '3'

services: 
    cas1: 
        container_name: cas1
        image: cassandra:latest
        volumes:
            - /var/lib/cassandra/data
        expose: 
            - 5555
        ports:
            - 9042:9042
        environment:
            - CASSANDRA_START_RPC=true
            - CASSANDRA_CLUSTER_NAME=MyCluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=datacenter1

    cas2:
        container_name: cas2
        image: cassandra:latest
        volumes:
            - /var/lib/cassandra/data
        ports:
            - 9043:9043
        command: bash -c 'sleep 60;  /docker-entrypoint.sh cassandra -f'
        depends_on:
        - cas1
        environment:
            - CASSANDRA_START_RPC=true
            - CASSANDRA_CLUSTER_NAME=MyCluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=datacenter1
            - CASSANDRA_SEEDS=cas1
            
    backend:
        build: ./ProcessingServer/dashboardBackend
        expose:
            - 8888
        ports: 
            - 127.0.0.1:5000:8888
            - $HOST_IP:50000:5000/udp

        depends_on: 
            - cas1 
        
        volumes:
            - ./ProcessingServer/dashboardBackend:/usr/src/app 
        environment: 
            - FLASK_ENV=development 
            - FLASK_APP=backendArduinoHomeSecurity.py 
            - FLASK_DEBUG=true
            - CASSANDRA_HOST=cas1 
            - HOST_IP=host.docker.internal
            
    frontend: 
        build: 
          context: .
          dockerfile: Dockerfile.prod
        expose: 
            - 3000 
        ports: 
            - 3000:80 
        links:
            - "backend:backend"
   

    
        

    # database: 
    #     extends: 
    #         file: ProcessingServer/dashboardBackend/database/docker-compose.yaml
    #         services: 
    #             - cas1 
    #             - cas2
                
